server:
  port: 0

spring:
  application:
    name: collector
  output:
    ansi:
      enabled: ALWAYS

grpc:
  server:
    port: 0
  client:
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
collector:
  kafka:
    producer:
      properties:
        bootstrap.servers: localhost:9092
        key.serializer: org.apache.kafka.common.serialization.VoidSerializer
        value.serializer: ru.yandex.practicum.ewm.stats.kafka.serializer.AvroSerializer
    topic:
      actions: "stats.user-actions.v1"

eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
    instance-id: collector:${random.value}