package ru.practicum.ewm.dto;

import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import ru.practicum.ewm.dto.event.NewEventDto;
import ru.practicum.ewm.model.Location;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

/// generated by Alisa
class NewEventDtoTest {

	private Validator validator;

	private final String validAnnotation = "Valid annotation text with more than 20 characters";
	private final String validDescription = "Valid description with more than 20 characters and less than 7000 chars";

	@BeforeEach
	void setUp() {
		try (ValidatorFactory factory = Validation.buildDefaultValidatorFactory()) {
			validator = factory.getValidator();
		}
	}

	@Test
	void whenValidDto_thenNoViolations() {
		NewEventDto dto = NewEventDto.builder()
				.annotation(validAnnotation)
				.category(1L)
				.description(validDescription)
				.eventDate(LocalDateTime.now().plusDays(1))
				.location(Location.builder()
						.lat(55.7558F)
						.lon(37.6173F)
						.build())
				.paid(true)
				.participantLimit(100)
				.requestModeration(true)
				.title("Valid title")
				.build();

		var violations = validator.validate(dto);

		assertEquals(0, violations.size());
	}

	@Test
	void whenAnnotationTooShort_thenViolation() {
		NewEventDto dto = NewEventDto.builder()
				.annotation("short")
				.category(1L)
				.description(validDescription)
				.eventDate(LocalDateTime.now().plusDays(1))
				.location(Location.builder()
						.lat(55.7558F)
						.lon(37.6173F)
						.build())
				.paid(true)
				.participantLimit(100)
				.requestModeration(true)
				.title("Valid title")
				.build();

		var violations = validator.validate(dto);

		assertEquals(1, violations.size());
		ConstraintViolation<NewEventDto> violation = violations.iterator().next();
		assertEquals("annotation", violation.getPropertyPath().toString());
		assertEquals("размер должен находиться в диапазоне от 20 до 2000", violation.getMessage());
	}

	@Test
	void whenCategoryIsNull_thenViolation() {
		NewEventDto dto = NewEventDto.builder()
				.annotation(validAnnotation)
				.category(null)
				.description(validDescription)
				.eventDate(LocalDateTime.now().plusDays(1))
				.location(Location.builder()
						.lat(55.7558F)
						.lon(37.6173F)
						.build())
				.paid(true)
				.participantLimit(100)
				.requestModeration(true)
				.title("Valid title")
				.build();

		var violations = validator.validate(dto);

		assertEquals(1, violations.size());
		ConstraintViolation<NewEventDto> violation = violations.iterator().next();
		assertEquals("category", violation.getPropertyPath().toString());
		assertEquals("не должно равняться null", violation.getMessage());
	}

	@Test
	void whenDescriptionTooLong_thenViolation() {
		String longDescription = "A".repeat(7001);
		NewEventDto dto = NewEventDto.builder()
				.annotation(validAnnotation)
				.category(1L)
				.description(longDescription)
				.eventDate(LocalDateTime.now().plusDays(1))
				.location(Location.builder()
						.lat(55.7558F)
						.lon(37.6173F)
						.build())
				.paid(true)
				.participantLimit(100)
				.requestModeration(true)
				.title("Valid title")
				.build();

		var violations = validator.validate(dto);

		assertEquals(1, violations.size());
		ConstraintViolation<NewEventDto> violation = violations.iterator().next();
		assertEquals("description", violation.getPropertyPath().toString());
		assertEquals("размер должен находиться в диапазоне от 20 до 7000", violation.getMessage());
	}

	@Test
	void whenEventDateIsNull_thenViolation() {
		NewEventDto dto = NewEventDto.builder()
				.annotation(validAnnotation)
				.category(1L)
				.description(validDescription)
				.eventDate(null)
				.location(Location.builder()
						.lat(55.7558F)
						.lon(37.6173F)
						.build())
				.paid(true)
				.participantLimit(100)
				.requestModeration(true)
				.title("Valid title")
				.build();

		var violations = validator.validate(dto);

		assertEquals(1, violations.size());
		ConstraintViolation<NewEventDto> violation = violations.iterator().next();
		assertEquals("eventDate", violation.getPropertyPath().toString());
		assertEquals("не должно равняться null", violation.getMessage());
	}

	@Test
	void whenLocationIsNull_thenViolation() {
		NewEventDto dto = NewEventDto.builder()
				.annotation(validAnnotation)
				.category(1L)
				.description(validDescription)
				.eventDate(LocalDateTime.now().plusDays(1))
				.location(null)
				.paid(true)
				.participantLimit(100)
				.requestModeration(true)
				.title("Valid title")
				.build();

		var violations = validator.validate(dto);

		assertEquals(1, violations.size());
		ConstraintViolation<NewEventDto> violation = violations.iterator().next();
		assertEquals("location", violation.getPropertyPath().toString());
		assertEquals("не должно равняться null", violation.getMessage());
	}

	@Test
	void whenTitleTooShort_thenViolation() {
		NewEventDto dto = NewEventDto.builder()
				.annotation(validAnnotation)
				.category(1L)
				.description(validDescription)
				.eventDate(LocalDateTime.now().plusDays(1))
				.location(Location.builder()
						.lat(55.7558F)
						.lon(37.6173F)
						.build())
				.paid(true)
				.participantLimit(100)
				.requestModeration(true)
				.title("ab")
				.build();

		var violations = validator.validate(dto);

		assertEquals(1, violations.size());
		ConstraintViolation<NewEventDto> violation = violations.iterator().next();
		assertEquals("title", violation.getPropertyPath().toString());
		assertEquals("размер должен находиться в диапазоне от 3 до 120", violation.getMessage());
	}
}
