CREATE SCHEMA IF NOT EXISTS users_service;

CREATE TABLE IF NOT EXISTS users_service.users (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email varchar(255) NOT NULL,
    name varchar(255) NOT NULL
);