CREATE SCHEMA IF NOT EXISTS users-service;

CREATE TABLE IF NOT EXISTS users-service.users (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users-service.users (email);