CREATE SCHEMA IF NOT EXISTS rating-service;

CREATE TABLE IF NOT EXISTS rating-service.ratings (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    event_id bigint NOT NULL,
    reaction varchar(10) NOT NULL CHECK (reaction IN ('LIKE', 'DISLIKE')),
);