CREATE SCHEMA IF NOT EXISTS request-service;

CREATE TABLE IF NOT EXISTS request-service.requests (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created timestamp(3) without time zone,
    status varchar(255) check (status in ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED')),
    event_id bigint,
    requester_id bigint
);


