CREATE SCHEMA IF NOT EXISTS event-service;

CREATE TABLE IF NOT EXISTS event-service.categories (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event-service.events (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    annotation varchar(2000) NOT NULL,
    created_on timestamp(3) without time zone NOT NULL,
    description varchar(7000) NOT NULL,
    event_date timestamp(3) without time zone NOT NULL,
    location jsonb,
    paid boolean NOT NULL,
    participant_limit integer NOT NULL,
    published_on timestamp(3) without time zone,
    request_moderation boolean NOT NULL,
    state varchar(255) check (state in ('PENDING','PUBLISHED','CANCELED')) NOT NULL,
    title varchar(120) NOT NULL,
    category_id bigint,
    initiator_id bigint,
    rate bigint NOT NULL DEFAULT 0,
    CONSTRAINT fk_events_categories FOREIGN KEY (category_id)
        REFERENCES event-service.categories (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS event-service.compilations (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    pinned boolean NOT NULL,
    title varchar(50) NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event-service.compilation_events (
    compilations_id bigint NOT NULL,
    events_id bigint NOT NULL,
    CONSTRAINT fk_events_compilations FOREIGN KEY (compilations_id)
        REFERENCES event-service.compilations (id) MATCH SIMPLE
        ON DELETE CASCADE,
    CONSTRAINT fk_compilations_events FOREIGN KEY (events_id)
        REFERENCES event-service.events (id) MATCH SIMPLE
        ON DELETE CASCADE
);