-- generated by gpt
CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users (email);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_categories_name ON categories (name);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL,
    created_on TIMESTAMP NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP NOT NULL,
    location CLOB,
    paid BOOLEAN NOT NULL,
    participant_limit INT NOT NULL,
    published_on TIMESTAMP,
    request_moderation BOOLEAN NOT NULL,
    state VARCHAR(255) NOT NULL,
    title VARCHAR(120) NOT NULL,
    category_id BIGINT,
    initiator_id BIGINT,
    rate BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_events_users
        FOREIGN KEY (initiator_id)
        REFERENCES users(id),

    CONSTRAINT fk_events_categories
        FOREIGN KEY (category_id)
        REFERENCES categories(id),

    CONSTRAINT chk_events_state
        CHECK (state IN ('PENDING','PUBLISHED','CANCELED'))
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created TIMESTAMP,
    status VARCHAR(255),

    event_id BIGINT,
    requester_id BIGINT,

    CONSTRAINT fk_requests_users
        FOREIGN KEY (requester_id)
        REFERENCES users(id),

    CONSTRAINT fk_requests_events
        FOREIGN KEY (event_id)
        REFERENCES events(id),

    CONSTRAINT chk_requests_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED'))
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    pinned BOOLEAN NOT NULL,
    title VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation_events (
    compilations_id BIGINT NOT NULL,
    events_id BIGINT NOT NULL,

    CONSTRAINT fk_events_compilations
        FOREIGN KEY (compilations_id)
        REFERENCES compilations(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_compilations_events
        FOREIGN KEY (events_id)
        REFERENCES events(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ratings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    reaction VARCHAR(10) NOT NULL CHECK (reaction IN ('LIKE', 'DISLIKE')),
    CONSTRAINT uq_ratings_user_event UNIQUE (user_id, event_id),
    CONSTRAINT fk_ratings_users FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_ratings_events FOREIGN KEY (event_id) REFERENCES events(id)
);