CREATE TABLE IF NOT EXISTS public.users (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users (email);

CREATE TABLE IF NOT EXISTS public.categories (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_categories_name ON categories (name);

CREATE TABLE IF NOT EXISTS public.events (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    annotation varchar(2000) NOT NULL,
    created_on timestamp(3) without time zone NOT NULL,
    description varchar(7000) NOT NULL,
    event_date timestamp(3) without time zone NOT NULL,
    location jsonb,
    paid boolean NOT NULL,
    participant_limit integer NOT NULL,
    published_on timestamp(3) without time zone,
    request_moderation boolean NOT NULL,
    state varchar(255) check (state in ('PENDING','PUBLISHED','CANCELED')) NOT NULL,
    title varchar(120) NOT NULL,
    category_id bigint,
    initiator_id bigint,
    rate bigint NOT NULL DEFAULT 0,
    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT fk_events_users FOREIGN KEY (initiator_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_events_categories FOREIGN KEY (category_id)
        REFERENCES public.categories (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.requests (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created timestamp(3) without time zone,
    status varchar(255) check (status in ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED')),
    event_id bigint,
    requester_id bigint,
    CONSTRAINT pk_requests PRIMARY KEY (id),
    CONSTRAINT fk_requests_users FOREIGN KEY (requester_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_requests_events FOREIGN KEY (event_id)
        REFERENCES public.events (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.compilations (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    pinned boolean NOT NULL,
    title varchar(50) NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.compilation_events (
    compilations_id bigint NOT NULL,
    events_id bigint NOT NULL,
    CONSTRAINT fk_events_compilations FOREIGN KEY (compilations_id)
        REFERENCES public.compilations (id) MATCH SIMPLE
        ON DELETE CASCADE,
    CONSTRAINT fk_compilations_events FOREIGN KEY (events_id)
        REFERENCES public.events (id) MATCH SIMPLE
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.ratings (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    event_id bigint NOT NULL,
    reaction varchar(10) NOT NULL CHECK (reaction IN ('LIKE', 'DISLIKE')),
    CONSTRAINT pk_ratings PRIMARY KEY (id),
    CONSTRAINT uq_ratings_user_event UNIQUE (user_id, event_id),
    CONSTRAINT fk_ratings_users FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_ratings_events FOREIGN KEY (event_id)
        REFERENCES public.events (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
